### ISSUE TITLE
Spin?

### ISSUE THREAD

**Issue by theClawsmos** [Akascape/TkDial#6]
How do you spin???? Please put in the README or bio how to spin the dials. Thanks :)

**Comment by Akascape** [comment]
@theClawsmos Use the .set method

**Comment by theClawsmos** [comment]
so you cant spin with mouse? cuz the .set method just sets the thing to be a certain float, right?

**Comment by Akascape** [comment]
@theClawsmos 
We can spin the dial with mouse (except the scroll knob and image knob), it's there by default.

**Comment by Akascape** [comment]
@theClawsmos Yes, you have to drag/click and it will follow the mouse. Why are you opening issues without testing anything?

**Comment by theClawsmos** [comment]
okay will try
