### ISSUE TITLE
Cannot install tkdial

### ISSUE THREAD

**Issue by xwillxw** [Akascape/TkDial#8]
`pip3 install tkdial` is returning `[SSL: CERTIFICATE_VERIFY_FAILED]`.
Please could this be fixed? I would like to use this library for a project.

**Comment by Akascape** [comment]
@willxwmusic 
Try `pip install tkdial` Or `python -m pip install tkdial`

**Comment by xwillxw** [comment]
was a problem on my end, solved by updating pip
